- app/scripts/TiledPixiTrack.js
- app/scripts/config.js
- app/scripts/debounce.js
Debounced zooming to avoid loading intermediate tiles, which wouldn't be displayed anyway.
> Debounced zooming

- app/scripts/HiGlassComponent.jsx
> Complements https://github.com/hms-dbmi/higlass-server/pull/29

- app/scripts/DraggableDiv.js
> Handles now seem correctly positioned on FF, and Chrome is unchanged.

- package-lock.json
- package.json
- webpack.config.js
Bundle size is down by 10% (100kb without gzip)
> Update to webpack v3

- app/scripts/api.js
> Make zoomTo example non-degenerate

- karma.conf.js
- package.json
In a different branch, my tests are stalling at some point, but I really can't tell which test is the problem. This prints out the name of each test as it is run and might help with debugging that.
> Verbose reporter

- PULL_REQUEST_TEMPLATE.md
- package.json
- webpack.config.js
Started creating a pull request template. Suggestions for what it should include are welcome.
> Started a pull request template

- docs/examples/1d-annotations.html
Initially added with https://github.com/higlass/higlass/pull/285
@mccalluc This track might be of interest to you
Docs are here: https://github.com/higlass/higlass-docs-dev/blob/master/track_types.rst#1d-annotations
> Re-add example

- README.md
> fix link for badge

- docs/higlass_server.rst
_What was changed in this pull request?_
Updated API documentation with `PATCH` call and tileset management commands.
_Why is it necessary?_
To update server documentation related to API changes (https://github.com/higlass/higlass-server/pull/80).
> Replaced PUT with PATCH cmd; added tileset management commands

- app/index.html
> Restore working index.html

- docs/examples/apis/load-annotations/main.js
- Use a hg38 chromsizes, because that's what this data is.
Looks the same: highlights on vertical and horizontal axes. Let me know if there's a better place to pull this from?
> hg38 for finn et al.

- docs/examples/examples.html
- docs/examples/regenerate.py
- Grid of examples and tracks used. Just a little bit gratuitous.
- Now that we know what track types are out there, make it easier to browse.
> tidier table

- README.md
This was suggested during the meeting today. This is one way to do it; there are others. [skip ci]
> Add link to slack on README

- README.md
*Wait until the diagram is actually what you want!*
- Show the current version of the diagram, and link to google draw so we'll know where it is and can edit.
- The downside of not checking in an exported image is that we won't keep the history, but seems much more maintainable.
- We have a lot of moving parts, and it's hard to know how they're related.
> related tools diagram

- app/scripts/GenomePositionSearchBox.js
- app/scripts/ViewHeader.js
- Sorted react props
- The warnings about these being out of order contributes a lot of noise to the log, and it seemed like an easy thing to do.
- There are a lot more in HiGlassComponent, but I'd worry about merge conflicts there.
> Sort react properties

- .eslintrc-minimal
- app/scripts/AxisPixi.js
- app/scripts/DragListeningDiv.js
- app/scripts/DraggableDiv.js
- app/scripts/HiGlassComponent.js
- app/scripts/SearchField.js
- app/scripts/SketchInlinePicker.js
> more linting

- .eslintrc-minimal
- app/scripts/mixwith.js
- app/scripts/utils/test-helpers.js
- Reorder definitions to satisfy `no-use-before-define`.
> Reorder definitions

- README.md
- fix readme link / change text.
> "svg" is now "svg.html"... but this feels more useful?

- .eslintrc
- .eslintrc-minimal
- Replace #487: To get this check to pass lots of code needed to be deleted, and tests were failing. Ignoring it instance by instance is another option, or maybe there is a real fix.
> ignore no-unused-state

- docs/data_preparation.rst
Fixes the bigwig ingestion commands.
Fixes: https://github.com/higlass/higlass-docs/issues/11
> Fix the bigwig examples (higlass-docs #11)

- app/scripts/CombinedTrack.js
- app/scripts/HiGlassComponent.js
- app/scripts/IdHorizontal1DTiledPixiTrack.js
- app/scripts/SeriesOptions.js
- app/scripts/TiledPlot.js
- app/scripts/ViewportTracker2DPixi.js
- app/scripts/d3-context-menu.js
- Towards enforcing `no-undef`
but there are still a number of problems I wasn't sure how to tackle:
```
higlass/app/scripts/Annotations2dTrack.js
368:5  error  'pubSub' is not defined  no-undef
416:7  error  'pubSub' is not defined  no-undef
higlass/app/scripts/d3-context-menu.js
92:9   error    'd3' is not defined          no-undef
93:9   error    'd3' is not defined          no-undef
232:27  error    'd3' is not defined          no-undef
233:26  error    'd3' is not defined          no-undef
250:29  error    'd3' is not defined          no-undef
251:28  error    'd3' is not defined          no-undef
267:5   error    'd3' is not defined          no-undef
268:5   error    'd3' is not defined          no-undef
higlass/app/scripts/SeriesOptions.js …
```
> toward no-undef

- docs/data_preparation.rst
More documentation about multivec files
- [o] Unit tests added or updated
- [o] Example added or updated
- [o] Screenshot for visual changes (e.g. new tracks)
- [o] Updated CHANGELOG.md
> Expand the documentation of multivec files

- app/scripts/HorizontalLine1DPixiTrack.js
- app/scripts/OverlayTrack.js
- app/scripts/Tiled1DPixiTrack.js
- docs/examples/viewconfs/overlay-tracks.json
- karma.conf.js
- test/Horizontal1DTrackTests.js
- test/view-configs.js
Fixed issues related to overlay drawing, showTooltip and misaligned mouseover.
https://github.com/higlass/higlass/issues/545
https://github.com/higlass/higlass/issues/544
> Fix mouseover, overlay extent and mouseover

- docs/data_preparation.rst
-Added section "States Data (multivec)" explaining the functionality of converting States Data format to multivec.
> Adding section for States Data (multivec)

- docs/tutorial.rst
Python 3 is necessary to run `higlass-manage`.
To let people know that that is the case.
> Mention Python 3 requirement

- docs/higlass_docker.rst
- docs/index.rst
- docs/jupyter.rst
> [WIP] higlass-python documentation updates

- docs/index.rst
replaces https://github.com/higlass/higlass-docs-dev/pull/4/files
> fix higlass.io link

- docs/higlass_server.rst
replace https://github.com/higlass/higlass-docs-dev/pull/5/files
> typo + line-ending whitespace

- docs/data_preparation.rst
Added a little more information about assemblies.
Clarify how beddb files are loaded.
Fixes #___
> Updated the docs with information about assemblies

- app/styles/Modal.module.scss
Fix taken from #649 
Fixes #656 #657
> What else?
The scroll broking is also already implemented in #649 
> Fix #656 Fix #657

- app/scripts/HiGlassComponent.js
- docs/examples/apis/get-min-max-value.html
- docs/examples/apis/load-annotations/index.html
- docs/examples/apis/zoom-to.html
- Remove references to non-existent css file.
Fixes #393
> Mccalluc/remove page.css

- PULL_REQUEST_TEMPLATE.md
- docs/developer.rst
- document how to validate by hand. (I thought about adding ajv-cli to development dependencies, but decided against it: Nothing actually uses it.)
- Pete requested: https://github.com/higlass/higlass/pull/682#issuecomment-501338917
> follow-up docs

- docs/data_preparation.rst
- docs/higlass_server.rst
* Added documentation for how to aggregate bed files as bedpe files
* Added a section on the POST API for tilesets
* Rearranged the server sections so they have a (slightly) more logical ordering.
Fixes #___
> Documentation updates

- docs/data_preparation.rst
Added a section to the docs describing how to create a bigwig file.
Fixes #___
> Added a short section on creating bigwig files

- CHANGELOG.md
- app/scripts/TiledPlot.js
- app/scripts/utils/visit-tracks.js
- karma.conf.js
- package-lock.json
- package.json
- test/UtilsTests.js
This PR fixes the replace track bug by making sure that the combined track is visited by `visitTracks`.
Fixes #___
> Fix the replace track bug

- docs/index.rst
- docs/jupyter.rst
> Update jupyter docs

- docs/README.md
> Fix out of date readme

- docs/tutorial.rst
- linewrapping
- whitespace
- download sample file in prerequisites
> wget sample data. (And some whitespace changes.)

- docs/jupyter.rst
Added a missing import statement in the docs.
To make the example work.
Fixes #___
> Add import statement to docs

- CHANGELOG.md
- app/scripts/utils/index.js
- app/scripts/utils/track-utils.js
Take some of the core track functionality outside of the inheritance hierarchy and place it into a utils function so that it can be used in a composable fashion.
To make it possible to create tracks without using our complex inheritance hierarchy.
Fixes #___
> Common trackUtils function

- docs/track_types.rst
Updated defunct URL to point to gene annotation creation documentation.
Follow-up to discussion on Slack channel https://higlass.slack.com/archives/CCDG12ZKP/p1571181815000800
> Updated gene annotation track creation URL

- docs/higlass_docker.rst
added docker networking config example - trying to address following issues:
https://github.com/higlass/higlass-manage/issues/34
https://github.com/higlass/higlass-docker/issues/148
@pkerpedjiev  - I did it finally! sorry for the delay.
> why is this neccessary ?
what happened to us was, that the default docker's IP-pool `172.17.x.x` was interfering with the WiFi router - which has an IP from the same subrange.
So docker was modifying the `route` table like so:
```
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.18.1.0      0.0.0.0         255.255.255.0   U     0      0        0 br-blahblahblah
```
and then the machine running this docker would get unavailable via Wi-Fi ...
Pretty nasty issue, and a bit hard to …
> [WIP] added docs for docker networking config example

- app/scripts/configs/datatype-to-track-type.js
- app/scripts/configs/options-info.js
- app/scripts/configs/tracks-info.js
- app/scripts/data-fetchers/genbank-fetcher.js
- app/scripts/hocs/with-modal.js
- app/scripts/hocs/with-pub-sub.js
- app/scripts/hocs/with-theme.js
- app/scripts/services/dom-event.js
- app/scripts/services/element-resize-listener.js
- app/scripts/services/tile-proxy.js
- app/scripts/utils/abs-to-chr.js
- app/scripts/utils/color-domain-to-rgba-array.js
- app/scripts/utils/dict-items.js
- app/scripts/utils/fill-in-min-widths.js
- app/scripts/utils/get-default-track-for-datatype.js
- app/scripts/utils/get-higlass-components.js
- app/scripts/utils/get-track-obj-by-id.js
- app/scripts/utils/gradient.js
- app/scripts/utils/interval-tree.js
- app/scripts/utils/is-within.js
- app/scripts/utils/ndarray-to-list.js
- app/scripts/utils/numericify-version.js
- app/scripts/utils/show-mouse-position.js
- app/scripts/utils/test-helpers.js
- app/scripts/utils/total-track-pixel-height.js
- app/scripts/utils/track-utils.js
- app/scripts/utils/value-to-color.js
- app/scripts/utils/visit-positioned-tracks.js
- app/scripts/utils/visit-tracks.js
Prettier has been run on more files.
It seems prettier has not been run on the entire codebase
Fixes #___
> Run prettier

- CHANGELOG.md
- app/scripts/LeftTrackModifier.js
- app/scripts/TrackRenderer.js
- app/scripts/configs/tracks-info.js
- docs/track_types.rst
- karma.conf.js
- test/EmptyTrackTests.js
This PR just adds an empty track.
So that we can have an empty PIXI track.
Fixes #___
> Empty track

- CHANGELOG.md
- app/scripts/DivergentBarTrack.js
- karma.conf.js
- test/HiGlassComponentTest.js
- test/view-configs-more/divergentTrackConfig.json
The Divergent Bar track was broken in the sense that actually a Bar track was rendered. This PR fixes this and improves the corresponding test. 
Divergent bar track is not rendered.
Fixes #___
> Fix divergent bar track

- docs/view_config.rst
Somewhere to point people to for doing this.
> valueScaleMin and valueScaleMax example

- CHANGELOG.md
- app/scripts/configs/tracks-info.js
Some options of horizontal tracks were missing in their vertical counterparts.
Fixes #883
> Consolidation of track options

- CHANGELOG.md
- app/styles/TiledPlot.module.scss
- Removed styles for the td tag
- Because it clobbers the styles for any containing application
Fixes #___
> Remove random td tag

- docs/view_config.rst
Fix overlay example:
- Added missing comma
- Harmonized object notation
- Fixed ridiculous outlineWidth
Fixes #939
> Fix overlay example. Close #939

- CHANGELOG.md
- app/scripts/services/tile-proxy.js
- package-lock.json
- Removes the text/plain encoding when requesting text
- Because it's not necessary. It also causes problems with presigned AWS urls
Fixes #___
> Remove text encoding

- app/scripts/HiGlassComponent.js
- test/APITests.js
- test/GeneAnnotationsTrackTests.js
- Track information does not need to be in `this.state` so take it out
- This fixes the failing tests
Fixes #___
> Fix plugin track storage to fix tests

- CHANGELOG.md
- app/scripts/HeatmapTiledPixiTrack.js
- package-lock.json
- package.json
- test/HiGlassComponentTest.js
- Fix multivec SVG export
Fixes #___
> Tiny PR to fix multivec SVG export

- docs/javascript_api.rst
- Autodoc the off function
Fixes #___
> Autodoc the off function

- package-lock.json
- package.json
- Update prettier  so that code is formatted with v2.0
Fixes #___
> Bump prettier version

- docs/data_preparation.rst
- Update to the bigWig ingestion docs based on feedback from Slack.
Fixes #___
> Update bigWig ingestion docs

- docs/javascript_api.rst
- Tiny docs update
- So that the `getLocation` function is documented in the Javascript API dos
Fixes #___
> Add getLocation to javascript api docs

- docs/javascript_api.rst
- Added `getLocation` to the Javscript api docs.
Fixes #___
> Aded getLocation to javascript api docs

- app/scripts/api.js
- Updated the docstring for `getTrackObject`
Fixes #___
> Added a docstring for  API function

- .github/workflows/nodejs.yml
- .github/workflows/npmpublish.yml
- package-lock.json
- Added GitHub actions
- Travis CI no longer works for creating builds
Fixes #___
> Added github actions scripts

- CONTRIBUTING.md
Added a line to the `CONTRIBUTING.md` describing our conventions for the CHANGELOG.
Clarification and future reference.
Fixes #___
> Update CONTRIBUTING.md to describe CHANGELOG convention

- .github/workflows/nodejs.yml
- karma.conf.js
- test/HiGlassComponent/existing-genome-position-search-box.js
- test/ViewManipulationTests.js
```diff
push:
branches: [master]
pull_request:
-    branches: [master]
```
This update will trigger GitHub actions on any PR so that we can see if tests are passing before we determine to merge the PR.
Fixes #___
> Remove the scope of PR branches for GitHub Actions

- karma.conf.js
Turned off the HiGlassComponent tests.
These tests are fickle and preventing a release. I've manually verified that the things being tested work.
Fixes #___
> Turn off higlasscomponent tests

- .github/workflows/ci.yml
adds `develop` branch to GH Action for `push` events
Fixes #___
> chore: run CI on develop & master branches

- README.md
> fix: build badge in readme

- package-lock.json
- package.json
> Allow React 17 as peerDependency

- CHANGELOG.md
- app/scripts/PixiTrack.js
- app/scripts/Track.js
- app/scripts/TrackRenderer.jsx
- app/scripts/hocs/with-pub-sub.jsx
- app/scripts/types.ts
- app/scripts/utils/type-guards.js
- package-lock.json
- package.json
- feat: Add types for Track.js
- feat: Add types for PixiTrack.js
Fixes #___
> feat: Add type annotations for `Track` and `PixiTrack`

- app/scripts/Autocomplete.jsx
- app/scripts/CustomTrackDialog.jsx
- app/scripts/GenomePositionSearchBox.jsx
- app/scripts/ListWrapper.jsx
- app/scripts/SortableList.jsx
- app/scripts/TiledPlot.jsx
- app/scripts/hocs/with-modal.jsx
- app/scripts/hocs/with-pub-sub.jsx
- app/scripts/hocs/with-theme.jsx
- app/scripts/icons.jsx
- add proptypes
- ignore prop-spreading in hocs
- the rest
Fixes #___
> chore: Fix or disable remaining eslint warnings

- .eslintrc.js
- .github/workflows/ci.yml
- tsconfig.json
- vite.config.js
- vite.config.mjs
- web-test-runner.config.mjs
Forces Vite pre-optimization for _all_ files when running the test running. This should hopefully help to avoid weird timeouts in CI.
Fixes #___
> test: force pre-optimize deps for testing

- app/scripts/data-fetchers/DataFetcher.js
- app/scripts/services/tile-proxy.js
- app/scripts/types.ts
> feat: typecheck DataFetcher

- app/globals.d.ts
- app/missing-types.d.ts
- package.json
- test/HorizontalMultivecTests.js
- web-test-runner.config.mjs
> chore: fix hori-multivec tests and format types

- app/scripts/utils/DenseDataExtrema1D.js
- app/scripts/utils/DenseDataExtrema2D.js
- package-lock.json
- package.json
> feat(typing): Annotate DenseDataExtrema

- .npmrc
- package-lock.json
- package.json
- vite.config.mjs
Bumps the versions for all things required by our build:
- esbuild
- Vite
- babel
Fixes #___
> chore(build): Update to latest build deps

- app/scripts/ChromosomeInfo.js
- app/scripts/HeatmapOptions.jsx
- app/scripts/HeatmapTiledPixiTrack.js
- app/scripts/data-fetchers/DataFetcher.js
- app/scripts/hocs/with-pub-sub.js
- app/scripts/utils/fake-pub-sub.js
Fix failing linting and type checks. 
Meant to merge develop into my other branch but accidentally did the other way around. Fixing what caused failing tests here 
Fixes #___
> fix: failing linting and type checks  

- scripts/vitest-browser-commands.mjs
- vitest.setup.js
Refactors caching to use a simpler layout with two handlers:
- `/tiles` and `/tileset_info`: Cache individual tiles/tilesets by ID,
merging on read.
- All other routes: Cache by path using a deterministic query param
normalization.
This improves readability and reduces complexity in route handling.
> test: Simplify mock fixture caching

- CHANGELOG.md
- app/scripts/TrackRenderer.jsx
- app/scripts/types.ts
- app/scripts/utils/flatten.js
- app/scripts/utils/reduce.js
- app/scripts/utils/visit-positioned-tracks.js
- test/utils.test.js
- test/view-configs.js
- **fix: `reduce` utility to have accumulator**
- **Update types and tests**
Fixes #___
> feat(typing): Annotate `flatten` and `reduce` utils (add tests)

- app/scripts/services/chrom-info.js
- app/scripts/services/index.js
- app/scripts/utils/get-track-position-by-uid.js
- app/scripts/utils/get-xylofon.js
- app/scripts/utils/has-parent.js
- app/scripts/utils/interval-tree.js
- app/scripts/utils/load-chrom-infos.js
- app/scripts/utils/segments-to-rows.js
- test/utils.test.js
- **Annotate `utils/get-track-position-by-uid.js` and add unit test**
- **Annotate `utils/get-xylofon.js`**
- **Annotate and unit test `IntervalTree` and `segmentsToRows`**
- **Annotate chrom-info helpers**
Fixes #___
> More utility type annotations

- app/scripts/services/tile-proxy.js
> Resolve original requests in tile proxy

- app/scripts/services/tile-proxy.js
Moves tile response merging logic into `indexTiles` for better
separation of concerns.
Fixes #___
> Refactor tile response handling by extracting `indexTiles` function

- app/scripts/TiledPixiTrack.js
> Cherry pick changes from resgless `TiledPixiTrack.js`

- docs/higlass_server.rst
Small modifications to server API documentation.
Current sample requests in documentation return an empty result, even if tilesets have been ingested.
> Adding missing forward slashes to tilesets URLs

- app/scripts/hglib.jsx
- app/scripts/types.ts
Uses a callback ref to resolve a promise for the `HiGlassComponent`
Fixes #___
> Use a callback ref to resolve `HiGlassComponent` promise from `hglib.launch`

- CHANGELOG.md
- app/scripts/ChromosomeGrid.js
- app/scripts/HiGlassComponent.jsx
- app/scripts/HorizontalChromosomeLabels.js
- app/scripts/TiledPixiTrack.js
- package-lock.json
- package.json
Rebased https://github.com/higlass/higlass/pull/1263 onto the v3 branch and fixed some typing.
Maintain parity between `develop` and `v2` branches
Fixes #___
> Chromsizes from tileset info v2

- app/scripts/Annotations1dTrack.js
- app/scripts/Annotations2dTrack.js
- app/scripts/BedLikeTrack.js
- app/scripts/ConfigViewMenu.jsx
- app/scripts/SeriesListMenu.jsx
- app/scripts/TiledPixiTrack.js
- app/scripts/TrackRenderer.jsx
- app/scripts/configs/index.js
- app/scripts/data-fetchers/local-tile-fetcher.js
- app/scripts/hglib.jsx
- app/scripts/options-info.js
- app/scripts/plugins/available-for-plugins.js
- app/scripts/services/worker.js
- app/scripts/test-helpers/test-helpers.jsx
- app/scripts/utils/default-tracks.js
- app/scripts/utils/index.js
- package-lock.json
- package.json
- test/api.test.js
- test/bedlike.test.js
- test/plugin-track.test.js
- test/view-configs-more/smallViewconf.json
* Update Annotations1d, Annotations2d and BedLike tracks.
* Add some more exports to the API
Fixes #___
> Update Annotations1d, Annotations2d and BedlikeTracks
