higlass/higlass

app/scripts/TileProxy.js
app/scripts/TiledPixiTrack.js
app/scripts/config.js
app/scripts/worker.js

The debouncing bundles the request by the TiledPixiTrack instances. The worker bundles the request by server and only sends of unique tile IDs (in case multiple instances request the same tile).
One important thing to note: right now the benefit is limited as the worker is relying on GET requests with URL encoding of tile ids, which is limited to 10 tiles per request. I'd suggest allowing POST requests on the server side and sending a JSON object with an array of all IDs. This would allow to send one request for an arbitrary large number of tiles.

Add request debouncing with bundling

---

app/scripts/HiGlassComponent.jsx

If there is a better idiom than an alert box, great. Depending on that, you might not want to clear the chooseTrackHandler state: Maybe just ignore invalid clicks until the user selects something which is good?

Do not allow viewport to be applied to self. Fix #68

---

app/restrict.html
app/scripts/HiGlassComponent.js
app/scripts/TiledPlot.js
app/scripts/TrackRenderer.js

Limit translation: is agnostic to initial zoom level, i.e., if you initialize by seeing everything you see everything but upon zooming in only the area within the limits will be panable.
E.g., the following allows only panning in chr12
```xDomainLimits: [1950914406, 1950914406 + 133851895],
yDomainLimits: [1950914406, 1950914406 + 133851895],```
Limit scale: you can also limit the scale but make sure to understand that this limit is relative and based on the initial domain. E.g., if you start off at chr12 then you cannot zoom out but only zoom in. If you start at chr1-chrM then you see everything
zoomLimits: [1, Infinity],

Add translate and scale limits

---

app/scripts/ConfigTrackMenu.js
app/scripts/ConfigViewMenu.js
app/scripts/ContextMenuItem.js
app/scripts/HiGlassComponent.js
app/scripts/SeriesListMenu.js
app/scripts/ViewContextMenu.js

- Adds "data-menu-type" to contextual menus to help identify what the menu is related to.
- Adds "data-menu-item-for" to contextual menu items to help identify them re: their contents.
In future, would be utilized by 4DN to selectively hide certain menu items/options, e.g.:
```css
.hg-popup > .ContextMenu-module_context-menu-2OwvL[data-menu-type="ConfigTrackMenu"] > .ContextMenu-module_context-menu-item-1HeVv[data-menu-item-for="Add series"] {
display: none;
}
```
----
Call `this.resizeHandler()` from `this.updateAfterResize` to update whether chromosome search input element is visible or not -- **[Preview](https://gyazo.com/c178d8edde927dcd75272884bcdcd812)**

Add some "data-" attributes to menu elements for targeting w. CSS3. + Resize ViewHeaders after parent resize.

---

app/scripts/HiGlassComponent.js
app/scripts/services/chrom-info.js
app/scripts/services/tile-proxy.js
app/scripts/worker.js

Not sure about the behavior of d3-requests.
I was a little confused by worker.js, but this looks like the appropriate translation if we're adding more to the init: (Request and fetch have the same signature.)
```javascript
headers = {'content-type': 'application/json'};
r = new Request('http://example.com', {headers});
console.log('Headers:', Array.from(r.headers.keys()));
console.log('Credentials:', r.credentials);
// Headers: Array [ "content-type" ]
// Credentials: omit 
headers = {'content-type': 'application/json'};
r = new Request('http://example.com', {'headers': headers, 'credentials': 'same-origin'});
console.log('Headers:', Array.from(r.headers.keys()));
console.log('Credentials:', r.credentials);
// Headers: Array [ "content-type" ]
// Credentials: same-origin
```

I think this is everywhere that same-origin is required.

---

app/scripts/HiGlassComponent.js

If you have only one view and you want to listen to its location changes you can now be lazy and do:
```javascript
const hgApi = hglib.viewer(document.getElementById('demo'), viewConfig, { bounded: true });
hgApi.on('location', (...location) => { console.log(...location); });
```
I.e., you don't have to specify the actual view id. By default if there's only one view and you haven't specified any view id HiGlass will pick the first (and only) available view.

Choose first view ID if `viewId` is undefined and there is only one few

---

app/scripts/HorizontalGeneAnnotationsTrack.js

30% opacity on SVG export gene annotations

---

package.json
webpack.config.js

There was a problem with the UglifyJs plugin not supporting ES6, not creating the minified script and breaking the build (https://travis-ci.org/higlass/higlass/builds/452686746).
This fixes that issue by replacing UglifyJS with the Terser plugin.

Replaced uglify with terser

---

app/scripts/HeatmapTiledPixiTrack.js

The heatmap mouseover value was change to match the color scale and use base 10 values.
Fixes #395
Small change, no checklist...

Base-10 log on heatmap mouseover

---

app/scripts/HorizontalLine1DPixiTrack.js

- We first create a list of segments, and then both renders use the same data structure for drawing.
- Previously, when the log was taken of 0, the chart would appear to be clipped, with different behavior on the rising and falling slopes. It is now consistent and correct between renderers
Fixes #345

Create a separate datastructure which both renderers use

---

app/scripts/AxisPixi.js
app/scripts/HeatmapTiledPixiTrack.js

- Heatmap scales in SVG export have the correct scale, and color defaults to black.
Fixes #344 
Related to PR #363, but that only handled problems relating to the colors drawn, not to the axis numbers and ticks.
left: before / right: after
top: pixi / bottom: svg

SVG Axis was missing bits from Pixi

---

app/scripts/HiGlassComponent.js
app/scripts/TrackRenderer.js
app/scripts/utils/clone-event.js
app/scripts/utils/forward-event.js

The key aspect is in `TrackRenderer` line 1903. Setting `e.forwarded = true;` in the `TrackRenderer`ensures that the `wheelHandler` in `HiGlassComponent` doesn't fire again when the wheel event from `track-renderer-event` bubbled all the way up to the `window` which the `domEvent` service is listening to.
Remove duplicated wheel events
Fixes #417

Fix duplicated wheel forwarding

---

app/scripts/api.js
test/APITests.js
test/view-configs.js

Can be useful for debugging
Adds `version` to HgApi.
To be able to determine the version of Hglib dynamically with JS. Useful for the version dialog in HGA.
- ~~[ ] Example added or updated~~
- ~~[ ] Screenshot for visual changes (e.g. new tracks)~~

Expose version

---

app/scripts/utils/test-helpers.js
karma.conf.js
test/MinimalViewconfTest.js
test/view-configs.js

- Add tests for trivial viewconfs. (Though maybe these are too trivial... should there be an error in cases like these?)
- Add another special case to test-helpers.js: `cross-rule` is another instance where we do not need to wait for tiles. (Would there be any way to determine from the outside if a particular track type is one we should wait for?)
- I stalled out on the cross-rule svg export earlier because the test I wanted to write kept failing, and I didn't understand why.

"cross-rule" is a another special case which is not waiting for anything

---

.eslintrc-minimal
app/scripts/Autocomplete.js
app/scripts/HiGlassComponent.js
app/scripts/TiledPlot.js
app/scripts/mixwith.js
travis_build_test.sh

- Running eslint on `.` seems to have suddenly gotten a lot slower, so limit to `app` and `tests`.
- `implicit-arrow-linebreak` enforced
- `react/jsx-sort-props` changed from warning to error: It was adding a lot of noise to the logs, and there weren't actually that many lines that needed to be reordered.

linting: arrow linebreak and jsx prop sorting

---

.eslintrc-minimal
app/scripts/HiGlassComponent.js
app/scripts/symbol.js

- give `symbol.js` a default export.
- enforce `import/prefer-default-export`

enforce import/prefer-default-export

---

.eslintrc-minimal
app/scripts/OverlayTrack.js

- enforce `import/no-named-as-default`

Remove extra export which confused the default

---

.eslintrc-minimal
app/scripts/Autocomplete.js
app/scripts/GenomePositionSearchBox.js

Locally, searching for a gene seems to work the same as before.
- Enforce no-children-prop
- My guess is the `children` attribute on PopupMenu was being ignored, since a child element was already supplied?

Enforce no-children-prop

---

.eslintrc
.eslintrc-minimal

Fix #496
- Ignore all accessibility linting: A lot of what this comes down to is being able to operate controls from the keyboard, and I just don't think that's plausible here.

ignore linting on jsx-a11y

---

package.json

Fixed the version of `eslint-plugin-react` to fix the broken build.
The latest version of `eslint-plugin-react` causes an error: https://github.com/yannickcr/eslint-plugin-react/issues/2095
Fixes #___

Fix eslint-plugin-react version to fix build

---

test/APITests.js

Turned of the independent API tests.
These tests would fail intermittently and our only solution was to restart. Better to turn them off until we figure out how to fix them.
- [o] Example added or updated
- [o] Screenshot for visual changes (e.g. new tracks)
- [o] Updated CHANGELOG.md

Removed the periodically broken test for API independence

---

app/scripts/api.js

Updating the zoomTo() documentation so it's clear getLocation() can be used to find coordinates.
zoomTo() asks for coordinates and a few examples are given. But it wasn't clear where the Absolute coordinates came from. getLocation() can get absolute coordinates from a view, so I am updating  the documentation to make it clear.

zoomToDoc: Adding docs to show how zoomTo can use getLocation.

---

docs/higlass_server.rst

Update the docs to include a sample tile response.
So one doesn't have to open the developer console to see what tile responses look like.

Add an example of a tile response

---

COMMANDS
docs/COMMANDS

Small PR to update the docs build reference commands.
I look at these commands whenever I rebuild the docs in the `higlass-docs-dev` and `higlass-docs` repos. Because the current procedure is to push the `docs` subtree to each of those repositories, the reference commands need to be up-to-date here.
This is like meta-documentation. Documentation about how to build the documentation.

Update docs build commands

---

docs/higlass_server.rst

- Added a couple lines in docs/higlass_server about using the `dt` parameter for chromsizes and gene-annotations.
- See: https://github.com/higlass/higlass/blob/carlvitzthum/server-docs-update/docs/higlass_server.rst#api
- My linter messed with some trailing spaces in the docs.
- Helps document helpful cases of using REST API.
Fixes #___

Added dt = chromsizes + gene-annotations docs to docs/higlass_server

---

docs/higlass_server.rst

The `APP_BASEPATH` setting can be used to specify where the higlass server should look for the admin interface.

Added doc about `APP_BASEPATH`

---

CHANGELOG.md
app/scripts/TiledPixiTrack.js

Fix an issue checking if the value limit is a valid number
Avoid setting `NaN` as the value limits. `Number.isNaN('cool stuff yo!')` would be `false` because `cool stuff yo!` is not `NaN`. One needs to explicitly convert the variable to a number first.

Convert to number before checking for NaN

---

CHANGELOG.md
app/scripts/HorizontalLine1DPixiTrack.js

This pull request allows line tracks to use either `tileset_info.tile_size` or `tileset_info.bins_per_dimension` to determine the number of data points in each tile.
At some point we began using both terms for specifying the size of a tile. As long as we use both we should check for both.
Fixes #___
- [o] Example added or updated
- [o] Screenshot for visual changes (e.g. new tracks)

Use bins_per_dimension or tile_size

---

app/scripts/TiledPixiTrack.js

Remove `..code-block::`
At http://docs.higlass.io/javascript_api.html#TiledPixiTrack.on, `..code-block::` shows up in the output.

@example is sufficient by itself

---

docs/javascript_api.rst

`>` -> `/>`
At least for me, React requires the `/` on self-closing tags... maybe there is some version which does not have that requirement?

closing slashes

---

CHANGELOG.md
app/scripts/AxisPixi.js
app/scripts/HeatmapTiledPixiTrack.js

Destroy sprites when necessary so that they're not maintained in PIXI's texture cache.
Slows down memory leaks.
Fixes #___

Destroy texture-containing elements

---

app/scripts/HiGlassComponent.js
app/scripts/TiledPlot.js
app/scripts/TrackRenderer.js
docs/examples/others/test_drag.html
karma.conf.js
test/APITests.js
test/LeftTrackModifierTests.js

There's really no reason why we need separate horizontal and vertical tracks. After this PR, any horizontal track that is added to a vertical position will be decorated with a `LeftTrackModifier` and work as if it were a vertical track.
- [o] Screenshot for visual changes (e.g. new tracks)

Allow any horizontal track to be vertical

---

CHANGELOG.md
app/scripts/HorizontalHeatmapTrack.js
package-lock.json
package.json

Use nearest neighbor interpolation for horizontal heatmaps. This matches the behavior in the 2D heatmaps and makes much more sense when zooming in.
Any other type of interpolation leads to blurry heatmaps when zooming in.
vs
- [o] Unit tests added or updated
- [o] Example added or updated

Switch to nearest neighbor interpolation for horizontal heatmap

---

app/scripts/HiGlassComponent.js

- remove period introduced in previous commit.
```
ad812a67d app/scripts/HiGlassComponent.js    (Peter Kerpedjiev 2019-06-03 22:47:20 -0700 2687)         if ('project_name' in track) { delete.track.project_name; }
```
- build fails
We do have tests, but this commit went straight to develop, and wasn't caught. :(
```
$ git log  --graph  --all
* commit 3e82ba052facfe703d6a3925829e99871d1fa5c2 (HEAD -> mccalluc/extra-period, origin/mccalluc/extra-period)
| Author: Chuck McCallum <chuck_mccallum@hms.harvard.edu>
| Date:   Tue Jun 4 11:40:13 2019 -0400
| 
|     Extra period caused syntax error
| 
* commit 050ff5f06fb7775d4dd33981d42b2eadc16ca98e (origin/develop, origin/HEAD, develop)
| Author: Peter Kerpedjiev <pkerpedjiev@gmail.com> …
```

Extra period caused syntax error

---

app/scripts/api.js
test/SchemaTests.js

- Check schema when we export json
- and also test re-exporting fixtures
- I think you suggested this?
(It's possible that this PR when combined with the ones to tighten the schema will produce errors that neither produced independently: I think this kind of scenario is exactly why travis starts two builds, so don't worry about it until we actually see a problem.)

Check schema when we export json, and also test re-exporting fixtures

---

CHANGELOG.md
app/scripts/OSMTilesTrack.js

Update the protocol from `http` to `https` for fetching OSM tiles.
With the `http` protocol Chrome is throwing CORS errors

Fix protocol to avoid CORS errors

---

.eslintrc
app/scripts/utils/test-helpers.js

- Change the status of two eslint rules
- Warnings we'll just ignore aren't that useful. `react-in-jsx-scope` was easy, so why not. On the other hand, `sort-comp` looks like a small number of errors:
```
higlass/app/scripts/Autocomplete.js
134:3   error    maybeScrollItemIntoView should be placed after setIgnoreBlur  react/sort-comp
higlass/app/scripts/HiGlassComponent.js
373:3   error    zoomStartHandler should be placed after setChromInfo  react/sort-comp
higlass/app/scripts/TiledPlot.js
163:3   error    waitForDOMAttachment should be placed after getIdealizedTrackPositionsOverlay  react/sort-comp
higlass/app/scripts/TrackArea.js
19:3  error  handleMouseEnter should be placed after getControls  react/sort-comp …
```

Elevate react-in-jsx-scope; ignore sort-comp

---

CHANGELOG.md
app/scripts/TiledPlot.js

Fixed an issue where padding and margin were mixed up and created a small offset in the positioning of the `center` and `gallery` tracks
Interaction-wise I don't think this glitch was noticeable because the padding is usually minor and all tracks were offset equally but it became noticeable in Scalable Insets. 
**Previously**:
**Now**:

Flekschas/fix minor issue with the positioning of track-related divs

---

CHANGELOG.md
app/scripts/HeatmapTiledPixiTrack.js

Treat `mirror_tiles = false` of `tilesetInfo` as a falsy value
Right now only `mirror_tiles = 'false'` will turn of tile mirroring. The boolean value should be treated equally otherwise it's confusing.
- ~[ ] Update schema.json if there are changes to the viewconf JSON structure format~

Support boolean values too

---

CHANGELOG.md
app/scripts/HiGlassComponent.js

Dynamically update HiGlass theme
Previously the theme was only set once on init. By in Jupyter the same HG instance is reused when a cell is called multiple time. So changing between themes didn't work previously.
- ~[ ] Update schema.json if there are changes to the viewconf JSON structure format~

Dynamically update dark theme when the options change

---

CHANGELOG.md
app/scripts/HiGlassComponent.js

The export as link dialog will now create links with the format `server/l/?d=uuid`. This will return a small dummy page with metadata for link unfurling.
So that we can use link unfurling in Slack and Twitter
Fixes #___

Switch to the new share link url

---

CHANGELOG.md
app/scripts/ViewConfigEditor.js
test/ViewConfigEditorTests.js

Remove the hold ALT feature as it's confusion and leads to a weird bug.
Fixes #732 
- ~[ ] Update schema.json if there are changes to the viewconf JSON structure format~

Remove the hold ALT feature as it's confusion

---

PULL_REQUEST_TEMPLATE.md

- Added a new check called `Set proper GitHub labels` as a reminder to add GitHub labels
- Minor changes to the wording
As the author, labels are easy to add and they give others a quick idea about the kind of PR.
- ~[ ] Update schema.json if there are changes to the viewconf JSON structure format~

Add check for setting proper GitHub labels to the PR template. Minor changes to the wording.

---

CHANGELOG.md
app/scripts/PlotTypeChooser.js
app/styles/PlotTypeChooser.css

Makes sure that track's icon sizes are limited to 20px x 20px.
External tracks (like the epilogos track) can define huge icons which take up a lot of space unnecessarily.
Fixes #___
Before:
After:

Limit icon size in plot type chooser

---

CHANGELOG.md
app/scripts/TiledPlot.js
app/scripts/api.js
docs/examples/others/test_drag.html

This PR adds an API call to let an external program show the track chooser (yellow overlay where the mouse is). It also enables the track chooser to respond to drag events in addition to mouse move events.
If we want to be able to drag something over a track we need a way to be able to show which track we're currently over.
Fixes #___

Add api call to show track chooser

---

CHANGELOG.md
app/scripts/PixiTrack.js
app/scripts/data-fetchers/genbank-fetcher.js
package-lock.json

Added a check for the genbank fetcher to see if a file is gzipped and improved the error handling to better inform when something goes wrong.
1. The genbank fetcher doesn't make the distinction between gzipped and regular content.
2. When errors occur it can be difficult to figure out what went wrong.
Fixes #___

Check whether genbank files are gzipped and better handle errors

---

CHANGELOG.md
app/scripts/HorizontalGeneAnnotationsTrack.js
app/scripts/OverlayTrack.js
app/scripts/TiledPlot.js
app/scripts/TrackRenderer.js

A few bug fixes.
1. Track orientation was not being populated because it's no longer added to the viewconf. Updated it to be properly updated.
2. Removed some unnecessary code which was preventing drawing when overlays were off the screen. This is all taken care of by the track mask so no need for it there.

Overlay track bug fixes

---

CHANGELOG.md
app/scripts/HorizontalRule.js
app/scripts/TrackRenderer.js
app/scripts/VerticalRule.js
test/RuleTests.js

This PR fixes a bug where rules in a loaded viewconf would move relative to the underlying data.
Rules should never move relative to the underlying data.
Fixes #___
- [o] Update schema.json if there are changes to the viewconf JSON structure format

Fix moving horizontal rules bug

---

CHANGELOG.md
app/scripts/data-fetchers/genbank-fetcher.js

Make sure to display "Loading..." when pulling tileset info for Genbank files.
If the `this.tilesetInfoLoading` variable isn't set, the track will display `Tileset info not found` while it's fetching the tileset info.
Fixes #___
- [o] Unit tests added or updated
- [o] Example(s) added or updated
- [o] Update schema.json if there are changes to the viewconf JSON structure format

Show Loading... when retrieving a tileset

---

CHANGELOG.md
app/scripts/HorizontalLine1DPixiTrack.js

In `HorizontalLine1DPixiTrack`, make sure that `this.valueScale` is set when calling `getMouseOverHtml()`
When mousing over a track, which has the tooltip enabled, too quickly, `getMouseOverHtml()` was called before `this.valueScale` was set.

Ensure that the valueScale is available

---

docs/data_preparation.rst

Steps still need better descriptions.
Fixes:
* `gzcat` and `zgrep` are esoteric (installing GNU utils on Mac). `zcat` should be available on most linux/mac environments.
* what were those virtualenv-wrapper and s3 commands doing there?
* provided download link for `exonU.py`

Start improving gene annotation track creation docs

---

CHANGELOG.md
app/scripts/AddTrackDialog.js
app/scripts/HiGlassComponent.js
app/scripts/PlotTypeChooser.js
app/scripts/TiledPlot.js
app/scripts/configs/default-tracks-for-datatype.js
app/scripts/utils/get-default-track-for-datatype.js
app/scripts/utils/index.js
app/styles/PlotTypeChooser.css
docs/track_types.rst
test/AddTrackTests.js

- Changed the default plot types for the PlotTypeChooser when adding new tracks. The defaults are defined in configs/default-tracks-for-datatype.js
- When adding multiple tracks with different datatype, each track is added with its respective default plot type. The plot type chooser is hidden.
- Slight UI change of the PlotTypeChooser
- The configuration in configs/default-tracks-for-datatype.js was not considered.
Fixes #65

alexander-veit/default plot types when adding tracks

---

docs/index.rst
docs/troubleshooting.rst

Created `troubleshooting.rst` in docs.
Added there how to fix empty page on FF on Linux.

Add troubleshooting section to docs

---

CHANGELOG.md
app/scripts/CrossRule.js
app/scripts/HorizontalRule.js
app/scripts/VerticalRule.js
test/SvgExportTest.js

`exportSVG` functions were added for VerticalRule, HorizontalRule, and CrossRule track components.
Horizontal, vertical, and cross rule lines are currently not included when exporting to SVG. Users may expect that these tracks will appear in exported files.
Fixes part of #516

SVG export for Rule tracks

---

CHANGELOG.md
app/scripts/TiledPlot.js
package-lock.json
package.json
test/ChromosomeLabelsTests.js

This PR fixes functionality in TiledPlot which adds a `position` field to track definitions before they are passed on to TrackRenderer.
If a horizontal track is placed in a vertical position, we can automatically render it as a vertical track by wrapping it in LeftTrackModifier. In order to do this `TrackRenderer` needs to know the position of the track. This PR adds that information.
Fixes #___

Fixed adding position to track defs

---

CHANGELOG.md
app/scripts/data-fetchers/genbank-fetcher.js
package-lock.json

For some reason, having these headers leads to errors on CORS requests with redirects. Removing them fixes it. Also added `redirect: follow` header which is helpful because lots of services redirect their URLs to S3 buckets.
Fix genbank fetching.
Fixes #___

Remove content-type header from genbank requests

---

CHANGELOG.md
app/scripts/api.js
test/APITests.js

This pull request adds the values `xRange` and `yRange` to the return value of the JS API `.getLocation()` function.
This will enable us to obtain the dimensions of a particular view via the API, which will be used to position things relative to the view in the `cistrome-higlass-wrapper` app.

Update hgc.api.getLocation return value object

---

app/scripts/TilesetFinder.js
app/scripts/TrackRenderer.js
test/ViewConfigEditorTests.js

This PR resets the zoomTransform in the TrackRenderer when a new viewConfig is loaded, e.g., via the view config editor.
When the zoomTransform is not reset, saving a modified or unmodified view config via the editor can lead to an unexpected displacement of the existing tracks (since the zoomTransform is applied again).
Fixes #855

Fixed the track displacement issue when saving view configs

---

CHANGELOG.md
app/scripts/HeatmapTiledPixiTrack.js

This adds the `image-rendering: pixelated` css to the `<image/>` tag of exported heatmap SVGs. This css property is explained in this blog post: https://css-tricks.com/almanac/properties/i/image-rendering/#article-header-id-0 Also, I updated the height attribute to use the canvas height property rather than a static value of 256, since now with the `selectRows` option of the `horizontal-multivec` track, the canvas height may not always be 256.
Fixes #862
- Browser
- Exported SVG before these changes
- Exported SVG after these changes

Update styles of exported heatmp svg:image tags

---

CHANGELOG.md
app/scripts/HiGlassComponent.js
app/scripts/TiledPlot.js
test/APITests.js

This pull request adds code to trigger the `.on('viewConfig', callback)` callback function upon track resizing events, including from dragging the <DraggableDiv /> components
There is currently no way to detect track resize events from outside HiGlass.
Fixes #867

Trigger the on viewConfig callback on track resize events

---

CHANGELOG.md
app/scripts/DataFetcher.js
app/scripts/utils/test-helpers.js
test/HiGlassComponentTest.js

Adds denseDataExtrema to divided tiles so that they don't blow up.
Fixes #___
- [o] Example(s) added or updated
- [o] Update schema.json if there are changes to the viewconf JSON structure format
- [o] Screenshot for visual changes (e.g. new tracks or UI changes)

Add denseDataExtreme to divided tiles

---

app/scripts/SeriesListMenu.js

This PR prevents Higlass from crashing when clicking on "Configure Series" in the track context menu. See #661.
Fixes #661

Prevent crash when clicking "Configure Series"

---

app/scripts/utils/fill-in-min-widths.js
test/HiGlassComponentTest.js
test/UtilsTests.js
test/view-configs-more/oneViewConfig.json

This PR adds support for zero-height/zero-width 1D tracks. If the `height`/`width` property of a track is set to `0`, it will be correctly rendered with zero height/width. Note that if `height` or `width` is set, the `minHeight`, `minWidth` options are ignored.
Fixes #887

Support zero-height tracks

---

CHANGELOG.md
app/scripts/HiGlassComponent.js
app/scripts/PixiTrack.js
test/HeatmapTests.js
test/LabelTests.js
test/view-configs/label-split-heatmaps.json

Heatmap labels can now be hidden.
Split heatmaps now allow different label and colorbar positions (they were fixed before). However, when creating a new split heatmap by setting`extend` of one track to `upper-right` / `lower-left`, labels and colorbars will be still automatically positioned in opposite corners.
Labels couldn't be hidden, split heatmap labels were always fixed.
Fixes #884 
Fixes #812

Fix heatmap label position bugs

---

CHANGELOG.md
app/scripts/HiGlassComponent.js

This PR makes sure that stacked heatmap tracks receive the correct configuration when added via the track context menu.
Fixes #888 
Fixes #803

Correctly configure stacked heatmap tracks when added via the track context menu

---

CHANGELOG.md
app/scripts/TrackControl.js

The track config menu was positioned improperly when the control button is clicked twice. This bug occurred mainly because `imgConfig` and `imgClose`, which are the variables that are used to get the position of the cursor (e.g., `imgConfig.getBoundingClientRect()`), store the lastly rendered `ref`, such as the `ref` of a center track shown in the gif below.
Before:
After:
Fixes #910

Properly position the track config menu when clicked twice

---

CHANGELOG.md
app/scripts/api.js
test/APITests.js

This PR adds the parameter `resolveImmediately` to the `setViewConfig` API function. If set to true, it makes sure that the resulting promise resolves. Currently, when a new viewconfig is set and no new data needs to be loaded, the promise returned by `setViewConfig` does not resolve.
Promise returned by `setViewConfig` does not always resolve.
Fixes #___

Make sure setViewConfig promise resolves

---

CHANGELOG.md
app/scripts/AddTrackDialog.js
app/scripts/HiGlassComponent.js
app/scripts/configs/tracks-info.js
package-lock.json

- Make gene annotations rotatable so that they can be added as a left track
Fixes #___

Make gene annotations rotatable so they can be added as a left track

---

CHANGELOG.md
app/scripts/configs/available-for-plugins.js
docs/available_to_plugins.rst

This makes `ChromosomeInfo` and `SearchField` classes available to plugins under a new `HGC.chromosomes` object.
I realized that these classes are required to build a plugin track for serverless chromsizes datasets.
Fixes #___

Add ChromosomeInfo and SearchField to AVAILABLE_FOR_PLUGINS

---

CHANGELOG.md
app/scripts/HiGlassComponent.js

Plugin track infos are pulled from `window.higlassTracksByType` instead of `this.pluginTracks` (if available)
Options that are defined within plugin tracks are currently not correctly passed into the plugin track constructor.
Fixes #___

Fix plugin track registration

---

CHANGELOG.md
app/scripts/HorizontalGeneAnnotationsTrack.js

- It ignores filler annotations when rendering gene annotations
Fixes #___

Ignore filler annotations when rendering gene annotation names

---

CHANGELOG.md
app/scripts/SeriesListMenu.js

- When changing the track type for a track, the `TRACKS_INFO_BY_TYPE` includes plugin track types so we should use that.
Fixes #___

Show all available track types

---

app/scripts/HorizontalMultivecTrack.js
package-lock.json

1) I customize `getMouseOverHtml` in `HorizontalMultivecTrack` so that the mouseover tooltip has a similar appearance to the `higlass-multivec` track used for epilogos tracks. This only affects viewconfs which have `heatmapValueScaling` defined in the track's `options`, where it is set to `categorical`. The tooltip is otherwise presented in the same way as before.
2) A mouseover event on the first row of a multivec track would return no value for `row_infos`. This is because the index of the first row (0) would return `false` in the test `else if (selectedRowIndex)`, which skips adding the row information. I instead test if `selectedRowIndex` is within the bounds of the `row_infos` array, to add that value.
3) Mouseover on the multivec track below …

Categorical mouseover appearance and first-/last-row bug patch

---

CHANGELOG.md
app/scripts/HorizontalChromosomeLabels.js
app/scripts/configs/tracks-info.js
docs/track_types.rst

- Show only the integer ticks in chromosome labels tracks (#981)
- Add an option to change the orientation of tick labels/lines (e.g., `reverseOrientation=true` can be useful for showing chromosome labels on the bottom of the matrix visualization).
Fixes #981

No decimals in chromosome labels and an option for tick orientation

---

CHANGELOG.md
app/scripts/HorizontalMultivecTrack.js

Prevent from app crash when `[]` is set to the `selectRows` option in multivec heatmaps
Fixes #989

Empty selectRows

---

CHANGELOG.md
app/scripts/HorizontalGeneAnnotationsTrack.js

This is a copy of https://github.com/higlass/higlass/pull/983 (already approved)
Had to start over due to some weird merge issues.
Fixes the mouseover for the gene annotation track
Currently the mouseover shows "Strand: undefined"
Fixes #___

Fix gene annotation mouseover

---

CHANGELOG.md
app/scripts/HeatmapTiledPixiTrack.js

- Check for a one-value valueScale and don't try to draw a colorbar in it
- The colorbar code errors out otherwise
Fixes #___

Fix colorbar error when valueScale is degenerate

---

CHANGELOG.md
app/scripts/HiGlassComponent.js
app/scripts/api.js
test/APITests.js
test/view-configs-more/simpleCenterViewConfig.json

This PR adds a `zoomToGene` API that allows zooming a HiGlass view to a location near a certain gene. The location of gene is searched based on view specs: `autocompleteServer` and `autocompleteId`.
```js
hgApi.zoomToGene(
'view-1', // view id
'MYC',    // gene name
2000      // duration of animated transition
);
```
This allows to reposition the center of a HiGlass view using a gene name, similar to a `zoomTo` API that instead uses absolute positions.
Fixes #___

Add a zoomToGene API

---

CHANGELOG.md
app/schema.json
app/scripts/HiGlassComponent.js

This PR adds a root-level option of viewConfig, `compactLayout` (default: `true`), that allows to use or disable compact layout of HiGlass views ([verticalCompact in ReactGridLayout](https://github.com/STRML/react-grid-layout/blob/master/test/examples/11-no-vertical-compact.jsx)). This way, vertical gaps can be placed between views w/o using arbitrary `empty` tracks.
```js
{ ...,
compactLayout: false,
views: [
{ ..., layout: { w: 12, h: 3, x: 0, y: 0 } },
{ ..., layout: { w: 12, h: 3, x: 0, y: 6 } }
]
}
```
Vertical gaps between views can be useful for some use cases.
Fixes #___

Add an option to disable compact layout of RGL

---

CHANGELOG.md
app/scripts/HiGlassComponent.js
app/scripts/api.js
test/APITests.js

This PR adds an API, `suggestGene`, that returns the list of top matching genes for a given keyword (e.g., 'MY'). The suggestions are based on view specs: `autocompleteServer` and `autocompleteId`.
```js
hgApi.suggestGene('aa', 'MY', (suggestions) => {
if(suggestions && suggestions.length > 0) {
console.log('Gene suggested', suggestions[0].geneName);
console.log('Chromosome', suggestions[0].chr);
console.log('Start position', suggestions[0].txStart);
console.log('End position', suggestions[0].txEnd);
}
});
```
Together with the `zoomToGene` API (#997), this can be useful when we want to support searching for genes on the interface that are placed outside of HiGlass views.
Fixes #___

Add a suggestGene API

---

CHANGELOG.md
app/schema.json
app/scripts/HiGlassComponent.js
docs/view_config.rst

If `zoomLimits` is not set, highest zoom resolution is 1bp.
Fixes #996

Prevent from zooming in too far by default

---

CHANGELOG.md
app/scripts/DataFetcher.js
app/scripts/TiledPixiTrack.js

Show visual clue when failed to fetch tileset info

---

CHANGELOG.md
app/scripts/ViewportTracker2D.js
app/scripts/ViewportTrackerHorizontal.js
app/scripts/ViewportTrackerVertical.js

Fix to properly initialize the style of 1D brushes (`viewport-projection-horizontal` and `viewport-projection-vertical`) by calling `rerender()`.
Fixes #___

Properly initialize the style of 1D brushes

---

CHANGELOG.md
app/scripts/HorizontalChromosomeLabels.js
app/scripts/TiledPixiTrack.js

This PR makes vertical labels, such as chromosome labels and "Loading..." labels, readable by flipping properly.
Some labels are unreadable in vertical tracks.
Fixes #1006
Fixes #1003  
Fixes #1010

Make vertical labels readable

---

CHANGELOG.md
app/scripts/configs/available-for-plugins.js
docs/available_to_plugins.rst
docs/plugin_datafetcher.rst
docs/plugin_track.rst

Added the built-in data fetcher classes and the `getDataFetcher` function to a new `dataFetchers` property in `AVAILABLE_FOR_PLUGINS`.
This is helpful for developing plugins that use advanced data fetching logic. I'm personally trying to implement a multi-tileset data fetcher, which could be made much simpler with access to `getDataFetcher`.
P.S. I don't have write access to HiGlass so I can't add any labels.

Add data fetchers to AVAILABLE_FOR_PLUGINS

---

CHANGELOG.md
app/scripts/configs/available-for-plugins.js

Updated the track list in `AVAILABLE_FOR_PLUGINS`.
I was specifically missing HorizontalTiled1DPixiTrack for [`higlass-dynseq`](https://github.com/kundajelab/higlass-dynseq), which works only when it is added to `AVAILABLE_FOR_PLUGINS`.

Fix tracks available in AVAILABLE_FOR_PLUGINS

---

CHANGELOG.md
app/scripts/TrackRenderer.js

This PR correctly setups initial scales of vertical tracks when the width of a center track is zero.
Previously, if the width of the center track is zero (e.g., no tracks are added to the center and vertical tracks use the full width of a view), the scale was not correctly determined (i.e., `min` and `max` values became the same in `d3.domain([min, max])`, [code](https://github.com/higlass/higlass/blob/7342071813c576dff34dcd31a89de43cf062010a/app/scripts/TrackRenderer.js#L616)). This led to showing an empty white space in the vertical tracks (refer to the screenshots below).
<details>
<summary>Example View Config</summary>
```js
{
"editable": false,
"zoomFixed": false,
"trackSourceServers": [
"//higlass.io/api/v1", …
```

Correctly setup initial scales of vertical tracks when the width of a center track is zero

---

CHANGELOG.md
app/scripts/HorizontalGeneAnnotationsTrack.js

The GeneAnnotation track uses `tile.tileData.strand` in various places, but it is actually undefined. This PR adds it in the `externalInitTile` function.
The SVG export ignores the colors of the strands, because this value is undefined
Fixes #___

Add strand info to tileData in GeneAnnotation track

---

package-lock.json
package.json

I've been working on several applications with both HiGlass/Gosling where I'm generating HTML on the fly for the web-browser. I'd like to avoid writing the HTML to disk, and instead load the content via a data url (e.g. `data:text/html,<doctype!><html><h1>Hey</h1></html>`). Currently this throws an unrecoverable error due to an edge case with the version of `pub-sub-es` that higlass is on. This can additionally be useful with `puppeteer` for taking screenshots:
```javascript
import puppeteer from "puppeteer";
let viewconf = JSON.stringify(...);
let html = `\
<!doctype html>
<head>
<link rel="stylesheet" href="https://unpkg.com/higlass@1.7/dist/hglib.css">
<script src="https://unpkg.com/react@17/umd/react.production.min.js"></script>
<script …
```

chore: bump pub-sub-es to latest

---

app/scripts/HiGlassComponent.js

fix: deprecation warning for pixi.js 6.x.x
The current script gives a deprecation warning when using the latest pixi.js
Not applicable

fix: deprecation warning for pixi.js@6.x.x

---

.github/workflows/nodejs.yml
CHANGELOG.md

Adds `--static-logging` flag to tests in CI. Makes the logs nicer to read. Also updates Changelog with Vite/web-test-runner stuff.
Fixes #___

chore: make CI logs nicer to read

---

test/HiGlassComponent/divergent-track.js

Fixes the broken SVG export test. 
The expect x/y positions for the expected svg elements are slightly different. I'm guessing this is due to the new testing environment and not a regression. I updated the positions in the test from this correct SVG export:
Fixes the last outstanding broken test.
Fixes #___

fix(test): Update final x position of exported SVG

---

app/scripts/TrackRenderer.jsx
app/scripts/data-fetchers/get-data-fetcher.js
test/PluginDataFetcherTests.js

Fixes broken tests in `PluginTrackTests.js` and `PluginDataFetcherTests.js`.
I'm not actually sure how this test was passing previously... The tests both check to make sure that `trackRenderer.avaiableForPlugins` is the same as `plugin.hgc`, BUT the `TrackRenderer` mutates HGC to add additional servies at runtime
- (prior to #1111) https://github.com/higlass/higlass/blob/04df604872ea820a190995f2b34f92fcd552a68b/app/scripts/TrackRenderer.js#L119-L121
- (after #1111) https://github.com/higlass/higlass/blob/dc2098eb4e738903fbc7da2dd0589416dced80d5/app/scripts/TrackRenderer.jsx#L119-L126
so `AVAILABLE_FOR_PLUGINS` will never be the same as `trackRenderer.avaiableForPlugins`.
use `trackRenderer.avaiableForPlugins` when initiating plugins instead of …

fix(test): HGC comparison tests for plugins

---

test/ViewportProjectionTests.js

Fixes broken test in `ViewportProjectionTests.js`. 
Test previously was looking for `style` attribute on SVG element instead of `fill` and `stroke`. The expected values also differend from what was specified in `viewConfig`.
to fix more tests broken by #1111 
Fixes #___

fix(test): ViewportProjectionTests.js

---

.git-blame-ignore-revs

Updates the `ignore-rev` commit hash with the hash for the squashed commit from #1129 . 
Fixes #___

chore: update ignore-rev commit hash

---

CHANGELOG.md
app/scripts/GenomePositionSearchBox.jsx
app/scripts/HiGlassComponent.jsx
app/scripts/icons.jsx

The GenomePositionSearchBox and the assembly selection has not been working correctly for quite some time. This PR fixes that. Furthermore, in the absence of 2D or vertical tracks the position info in the search box only shows the x-coordinates now.
GenomePositionSearchBox was not working
Fixes #___

Fix GenomePositionSearchBox

---

CHANGELOG.md
app/scripts/GenomePositionSearchBox.jsx
test/HiGlassComponent/existing-genome-position-search-box.js

- Correctly set the selected assembly on startup.
- Hide position text in genome position search box when assembly is invalid or not set.
Currently the genome position search box does not show the correct assembly on startup in the select element (i.e., the one from the viewconfig).
Fixes #___

Set selected assembly on startup

---

CHANGELOG.md
package-lock.json
package.json

- fix: allow React 18 as peer dependency
- chore: update changelog
Allows a more flexible semver range for react/react-dom as a peer dependency. @keller-mark has had some success with using React 18 with HiGlass in Vitessce, and adding this to the `package.json` will allow folks to allow more flexible installs of HiGlass.
In the longer term, we should test different version of React, but this seems like the most flexible "fix" at the moment.
Fixes #___
I bumped the React dependency locally to 18, and things seem to work fine. There is just a console err from using `ReactDOM.render`, which says it's falling back to React 17 functionality. Users of the HiGlass component won't run into this issue. …

feat: Allow React v18 as peer dependency

---

package.json

Adds an entrypoint `hglib.css`
Now that higlass is behaving properly as a ES module, vite yells at you if you try to access 'higlass/dist/hglib.css'. 
```
[ERROR] Missing "./dist/hglib.css" specifier in "higlass" package [plugin vite:dep-scan]
editor/index.tsx:6:7:
6 │ import 'higlass/dist/hglib.css';
```
We could also come up with another name for this entry point. Perhaps just "./css" or something.

feat: entrypoint for higlass/dist contents 

---

package-lock.json
package.json
scripts/build.mjs

Uses the `vite-plugin-babel` to transform individual files rather than the babel API. Babel is still required as a part of our build because we need to transpile ES6 class syntax to ES5 for plugins. Rather than mixing and matching build tools, this uses babel within Vite (which should be much easier to maintain going forward.
Fixes #___

fix: Simplify babel usage in the build

---

CHANGELOG.md
package-lock.json
package.json
scripts/build.mjs

Historically users need to require both `hglib.css` and `hglib.js` in their HTML templates and bundler code. 
```html
<link rel="stylesheet" href="https://unpkg.com/higlass@1.13/dist/hglib.css">
<script src="https://unpkg.com/react@17/umd/react.production.min.js"></script>
<script src="https://unpkg.com/react-dom@17/umd/react-dom.production.min.js"></script>
<script src="https://unpkg.com/pixi.js@6/dist/browser/pixi.min.js"></script>
<script src="https://unpkg.com/higlass@1.13/dist/hglib.min.js"></script>
```
This requires that users keep the versions in sync over time in the HTML template. 
This PR injects the final CSS via JS, eliminating the need to also have `hglib.css` in the template:
```diff
--  <link rel="stylesheet" href="https://unpkg.com/higlass@1.13/dist/hglib.css">
<script …
```

feat: Inject CSS via JS in final HiGlass build

---

CHANGELOG.md
app/scripts/TiledPlot.jsx

For whatever reason, the `evtJson` is often a `boolean` here:
```js
if (!(datatype in DEFAULT_TRACKS_FOR_DATATYPE) && !evtJson.defaultTracks) {
console.warn('unknown data type:', evtJson.higlassTrack);
return undefined;
}
```
and therefore `evtJson.defaultTracks` is `undefined`, leading to the console erroring:
```
unknown data type: undefined
```
consistently.
I've seen this log for ages in both Gosling.js and HiGlass but never had the time to
look very deeply into it.
Fixes #___

fix: Disable logging unknown data-type in console

---

CHANGELOG.md
app/scripts/HeatmapTiledPixiTrack.js
app/scripts/SeriesListMenu.jsx
app/scripts/SeriesListSubmenuMixin.jsx
app/scripts/TiledPlot.jsx
docs/javascript_api.rst
package-lock.json
package.json
test/ContextMenuTests.js
test/utils/dom.js

- This PR allows tracks to supply their own context menu items
- This is necessary because may want to provide custom values depending on where the context menu was opened. See the example of the pileup track sorting by base at particular position. In this case, clicking on the "Sort by base" option adds a viewconfig option specific to the location clicked:
```
"sortByBase": {
"chr": "chr1_pat_hsa1",
"pos": 2104160
}
```
https://github.com/user-attachments/assets/e03205b8-4460-4e18-9c87-7af7dccd2ad9
Fixes #___

feat: Allow tracks to pass in custom context menu items

---

app/scripts/data-fetchers/DataFetcher.js

This change replaces the `#` syntax for private class attributes with
the `_` convention. The legacy ES5 transformation for classes appears to
have compatibility issues with the `#` syntax, breaking the build.
While `#` provides "true" private encapsulation in JavaScript, the `_`
convention is probably sufficient for our use case. This approach
maintains compatibility with legacy requirements for plugins and ensures
a successful build.
Fixes #___

Switch to `_` for private class attributes to resolve build issues

---

CHANGELOG.md
app/scripts/MapboxTilesTrack.js
app/scripts/PixiTrack.js
app/scripts/RasterTilesTrack.js
app/scripts/TiledPixiTrack.js
app/scripts/UnknownPixiTrack.js
index.html

Make tracks use `setError` for setting error texts. This lets one track set multiple errors by using the `source` parameter.
So that tracks can set and display multiple errors. If this functionality wasn't there, the different overlaps would overlap and be illegible.
Fixes #___

Use setError for track error handling

---

app/scripts/types.ts
app/scripts/utils/background-task-scheduler.js
app/scripts/utils/color-domain-to-rgba-array.js
app/scripts/utils/expand-combined-tracks.js
app/scripts/utils/fill-in-min-widths.js
app/scripts/utils/type-guards.js
test/utils.test.js

Add more type annotations (and unit tests) for various utilities
- **Annotate `utils/color-domain-to-rgba-array.js`**
- **Annotate `utils/expand-combined-tracks.js`**
- **Annotate types for `app/scripts/utils/fill-in-min-widths.js`**
Fixes #___

Add more type annotations for various `util`

---

app/scripts/utils/get-default-track-for-datatype.js
test/utils.test.js

Annotate types and add unit tests for `utils/get-default-track-for-datatype.js`

---

app/scripts/AddTrackDialog.jsx
app/scripts/HiGlassComponent.jsx
app/scripts/TiledPlot.jsx
app/scripts/TilesetFinder.jsx
app/scripts/TrackRenderer.jsx
app/scripts/configs/themes.js
app/scripts/hocs/with-modal.jsx
app/scripts/hocs/with-pub-sub.js
app/scripts/hocs/with-theme.jsx
app/scripts/utils/get-higlass-components.js

Adds type annotations for HOCs to preserve instance API
This ensures the wrapped component retains the same instance API while removing
the need to pass wrapped props (e.g., `modal`) explicitly.
Since TypeScript lacks Higher Kinded Types (HKT), we preserve the original type
instead. Potential instantiation errors (e.g., missing `modal`) are acceptable
as we control instantiation, and this approach maintains better type safety for
consumers.
Fixes #___

Annotate Higher Order React Components

---

app/scripts/services/tile-proxy.js
test/tile-proxy.test.js

Although `throttleAndDebounce` has a generic name, the function signature is coupled to `fetchMultiRequestTiles`. 
For example, I would expect such function to work like:
```ts
const debounced = throttleAndDebounce((item: string) => console.log(item), 100, 100);
setInterval(() => {
debounced("hi"); // 
}, 10);
```
However, after reviewing the implementation, I realized that `throttleAndDebounce` is actually an _aggregator_. It collects multiple calls and submits them in batches to the provided function, which operates on the aggregated input rather than individual requests.
This PR decouples it by changing the type signature, explicitly transforming a function that processes a batch `(items: Array<T>) => void` into one that handles individual items `(item: T) => void` (thus a rename to …

Refactor tile proxy batching to make aggregator generic

---

app/scripts/services/tile-proxy.js
test/tile-proxy.test.js

As a first step, moves the server-bundling of requests into a helper
which we can unit test separately.
Fixes #___

Extract and unit test server-bundling logic in tile-proxy

---

app/scripts/data-fetchers/DataFetcher.js
app/scripts/services/tile-proxy.js
app/scripts/services/worker.js
app/scripts/types.ts
app/scripts/utils/assert.js
test/tile-proxy.test.js

Refactor `delayedBatchExecutor` to return Promises
This PR updates `delayedBatchExecutor` to create internal promises and
resolvers, removing the need for a done callback in batched objects.
Before it required the called to pass in a callback:
```js
const tileData = await new Promise(done =>
tileProxy.fetchTilesDebounced({ ...request, done })
);
```
Now it cleanly is like this:
```js
const tileData = await tileProxy.fetchTilesDebounced(request);
```

Refactor `delayedBatchExecutor` to create resolvers internally

---

CHANGELOG.md
app/scripts/HeatmapTiledPixiTrack.js
app/scripts/HiGlassComponent.jsx
test/api.test.js

This pull request adds the properties `trackUid` and `viewUid` to the object that is published on wheel events (that have been registered via `.on('wheel', callback)` using the JS API).
Currently, wheel events only publish the track with which they are associated. However, this could be ambiguous if one wants to identify the track since there is no information about the parent view. To be more precise about which track a wheel event is associated with, we can also include the view UID in the event object.
Fixes #___

Publish viewUid and trackUid with wheel events

---

app/scripts/HiGlassComponent.jsx
package-lock.json

Move class var in HiGlassComponent to constructor
This fixes a build error encountered when running `npm run build`:
```
[babel-plugin] /Users/pete/projects/higlass/app/scripts/HiGlassComponent.jsx: Missing class properties transform.
99 |
100 | class HiGlassComponent extends React.Component {
> 101 |   topDivRef = React.createRef();
|   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
102 |
103 |   constructor(props) {
104 |     super(props);
```
Fixes #___

Move class var in HiGlassComponent to constructor

---

CHANGELOG.md
app/scripts/api.js
test/api.test.js

The previous `hideTrackChooser` API call was calling a non-existent `this` object. This PR fixes it and adds a test.
Prevent an error when calling `hideTrackChooser`.
Fixes #___

Fixed the hideTrackChooser API call

---

app/scripts/utils/show-mouse-position.js

When the `showMousePosition` option is set to `true` and the mouse pointer moves over a non-2d track, x and y values are published internally that can cause another 2d track to draw nonsensical vertical or horizontal lines. This test clears the relevant value so that it cannot be used to render such lines.
Fixes #814

Prevent erroneous lines on 2D tracks by clearing stale mouse position data

---

app/scripts/hglib.jsx
package.json
scripts/build.mjs
tsconfig.emit.json
tsconfig.json

Fixes #1108 
Adds the export of TypeScript types as a part of the build process. Using HiGlass as a library will now have autocomplete.
**`hg.viewer` docs**
**inline docs for `api`**
There is a lot more to do to make some of inline documentation use proper JSDoc annotations to get nicer in-editor rendering, but it's really nice to have these "hover" docs working!

Emit TypeScript types

---

app/scripts/Autocomplete.jsx
index.html
package-lock.json
package.json

Removes `dom-scroll-into-view` dependency with [`element.scrollIntoView`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) Web API.
Removes a dependency for something the browser does automatically.
Fixes #___

Replace `dom-scroll-into-view` dependency with `element.scrollIntoView`

---

app/scripts/HiGlassComponent.jsx
package-lock.json
package.json

Removes the `url-parse` dependency in preference of `URL.canParse` and `URL`.
Removes unecessary dependencies.
Fixes #___

chore: Drop `url-parse` for builtin browser parsing

---

CHANGELOG.md
app/scripts/ChromosomeGrid.js
app/scripts/HiGlassComponent.jsx
app/scripts/HorizontalChromosomeLabels.js
app/scripts/TiledPixiTrack.js
package.json

- Support loading chromsizes from a tileset info object
- This lets us support passing in chromsizes in higlass-python as part of tileset objects
Fixes #___

feat: Support loading chromsizes from tileset info

---

app/scripts/ConfigViewMenu.jsx
app/scripts/SeriesListMenu.jsx
app/scripts/configs/index.js
app/scripts/configs/options-info.js
app/scripts/hglib.jsx
app/scripts/plugins/available-for-plugins.js

- Moved options-info to configs folder
- Consistency with other options
Fixes #___

Move options-info to configs folder
